### ISSUE TITLE
Erroneous stack traces during player join

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#29]
```python
Logged from file connectionpool.py, line 435
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: u'plugin'
```

This is related to the log.py refactor (#27) and one of our formatters, will be investigated for Patch 2

**Comment by JasonBristol** [comment]
Down the road I would like to implement a custom logging.Filter and maybe subclass logging.Logger so we can spin up only one Logger and allow plugins and other modules to leverage it. This would be more efficient since currently a Logger will be spun up for each plugin.

The challenge here is to access a plugins name cross-module. This will need to be considered as we continue cleanup and refractor.
