### ISSUE TITLE
Issue in args & argsAfter helper functions

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#35]
I type "/perms users SurestTexas00 info" and the console reads:

```
[11:56:03] [Wrapper.py/INFO]: SurestTexas00 executed: /perms u s e r s   S u r e s t T e x a s 0 0   i n f o
[11:56:03] [Wrapper.py/ERROR]: Formulating CHAT_MESSAGE failed (local variable 'args' referenced before assignment)
Traceback (most recent call last):
  File "/home/surest/Desktop/server test/wrapper/proxy/client.py", line 388, in parse
    "args": argsAfter(chatmsg.split(" "), 1)
  File "/home/surest/Desktop/server test/wrapper/core/events.py", line 35, in callEvent
    if not self.wrapper.commands.playerCommand(payload):
  File "/home/surest/Desktop/server test/wrapper/core/commands.py", line 401, in playerCommand
    command = args(payload["args"], 0)
UnboundLocalError: local variable 'args' referenced before assignment
```

**Comment by JasonBristol** [comment]
This should be a quick fix since it appears to be localized to our helper functions, I will investigate and have a PR by EOD

**Comment by suresttexas00** [comment]
I am working on a Change right now to commands.py that ought to make things a little clearer... i will push it directly to experimental now since you might be working on this file too... please pull the changes if you can

**Comment by suresttexas00** [comment]
So here it is:
```
surest@surest-Satellite-L55-B ~/Desktop/server test $ python "/home/surest/Desktop/server test/wrapper/"
[14:49:26] [Wrapper.py/INFO]: Logging configuration file logging.json located and loaded, logging configuration set!
[14:49:26] [Wrapper.py/INFO]: **** Debugging is Enabled! ****
[14:49:26] [Wrapper.py/INFO]: Wrapper.py started - Version 0.7.7 (development build #111)
[14:49:26] [Wrapper.py/INFO]: Loading plugins...
[14:49:26] [Wrapper.py/INFO]: Loading plugin portals.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin Toolbox.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin simple.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin global.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin mcperms.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin help.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin global.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin stafftools.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin global.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin vanillaclaims.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin regions.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin SurestLib.py...
[14:49:26] [Wrapper.py/WARNING]: Plugin 'SurestLib' disabled - not loading
[14:49:26] [Wrapper.py/INFO]: Loading plugin SurestLib.py...
[14:49:26] [Wrapper.py/WARNING]: Plugin 'SurestLib' disabled - not loading
[14:49:26] [Wrapper.py/INFO]: Loading plugin vanillaclaims.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin signs.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin broadcaster.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin mcperms.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin regions.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin Teleports.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin global.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin chat.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin global.py...
[14:49:26] [Wrapper.py/INFO]: Loading plugin mcperms.py...
[14:49:26] [Wrapper.py/INFO]: Starting server...
[14:49:29] [Server thread/INFO]: Starting minecraft server version 1.9.2
[14:49:29] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[14:49:29] [Server thread/INFO]: Loading properties
[14:49:29] [Server thread/WARN]: ressource-pack-hash is depricated and found along side resource-pack-sha1. resource-pack-hash will be ignored.
[14:49:29] [Server thread/INFO]: Default game type: SURVIVAL
[14:49:29] [Server thread/INFO]: Generating keypair
[14:49:30] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25541
[14:49:30] [Server thread/INFO]: Using epoll channel type
[14:49:30] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[14:49:30] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[14:49:30] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[14:49:30] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[14:49:30] [Server thread/INFO]: Preparing level "worldx"
[14:49:30] [Server thread/INFO]: Preparing start region for level 0
[14:49:31] [Server thread/INFO]: Preparing spawn area: 4%
[14:49:32] [Server thread/INFO]: Done (2.203s)! For help, type "help" or "?"
[14:49:32] [Wrapper.py/INFO]: Server started
[14:49:56] [Server thread/INFO]: Turned off world auto-saving
[14:53:53] [Wrapper.py/ERROR]: Client Packet EOF (Packet was zero length, disconnecting)
Traceback (most recent call last):
  File "/home/surest/Desktop/server test/wrapper/proxy/client.py", line 637, in handle
    pkid, original = self.packet.grabPacket()
  File "/home/surest/Desktop/server test/wrapper/proxy/packet.py", line 62, in grabPacket
    length = self.unpack_varInt()
  File "/home/surest/Desktop/server test/wrapper/proxy/packet.py", line 95, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "/home/surest/Desktop/server test/wrapper/proxy/packet.py", line 379, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting
[15:04:28] [Server thread/INFO]: [Server] World is saving... (Expect lag)
[15:04:28] [Server thread/INFO]: Saving...
[15:04:28] [Server thread/INFO]: commands.save.flushStart
[15:04:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (worldx): All chunks are saved
[15:04:28] [File IO Thread/INFO]: ThreadedAnvilChunkStorage (worldx): All chunks are saved
[15:04:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:04:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:04:28] [Server thread/INFO]: commands.save.flushEnd
[15:04:28] [Server thread/INFO]: Saved the world
[15:04:28] [Server thread/INFO]: [Server] World saved.
[15:13:13] [Wrapper.py/ERROR]: Client Packet EOF (Packet was zero length, disconnecting)
Traceback (most recent call last):
  File "/home/surest/Desktop/server test/wrapper/proxy/client.py", line 637, in handle
    pkid, original = self.packet.grabPacket()
  File "/home/surest/Desktop/server test/wrapper/proxy/packet.py", line 62, in grabPacket
    length = self.unpack_varInt()
  File "/home/surest/Desktop/server test/wrapper/proxy/packet.py", line 95, in unpack_varInt
    val = struct.unpack('B', self.recv(1))[0]
  File "/home/surest/Desktop/server test/wrapper/proxy/packet.py", line 379, in recv
    raise EOFError("Packet was zero length, disconnecting")
EOFError: Packet was zero length, disconnecting
[15:13:16] [Wrapper.py/INFO]: Starting new HTTPS connection (1): sessionserver.mojang.com
[15:13:16] [Wrapper.py/INFO]: Starting new HTTPS connection (1): api.mojang.com
[15:13:17] [Wrapper.py/INFO]: SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a612-fb4230588eff | IP: 68.50.227.172)
[15:13:17] [Server thread/INFO]: SurestTexas00[/127.0.0.1:52643] logged in with entity id 173 at (3344.632057674222, 67.0, 2791.9095641583)
[15:13:17] [Server thread/INFO]: SurestTexas00 joined the game
[15:13:34] [Wrapper.py/INFO]: SurestTexas00 executed: /help 
[15:13:41] [Wrapper.py/INFO]: SurestTexas00 executed: /van j o i n
/this happens
[15:14:12] [Wrapper.py/ERROR]: Invalid command -- this
[15:14:24] [Wrapper.py/INFO]: SurestTexas00 executed: /this h a p p e n s   w i t h   a n y   c o m m a n d
```

**Comment by suresttexas00** [comment]
This may shed some additional light... comparing the console with the client chat output:

![image](https://cloud.githubusercontent.com/assets/10001762/14477983/caea7dbe-00df-11e6-865b-0075f8865eb1.png)


The second letter of the second word gets parsed as the second argument.

**Comment by JasonBristol** [comment]
I am currently working on resolving this, should have something to pull soon
